[build]
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200
  force = true

[[redirects]]
  from = "/index.css"
  to = "/assets/css/index.css"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/index.css"
  [headers.values]
    Content-Type = "text/css"